algoritmo "Operadores"
      var
      num1:inteiro
      num2:inteiro
      bol1:logico
      bol2:logico
      tex1:caracter
      tex2:caracter
      resultado:caracter
      dados:real
   inicio
   num1 <-10
   num2 <-5
   bol1 <-verdadeiro
   bol2 <-falso
   tex1 <-"alan "
   tex2 <-"faraj"
   escreval ( tex1 + tex2 )
   escreval ("Digite um valor para variável DADOS")
   leia (dados)
   fimalgoritmo
